source 'https://github.com/CocoaPods/Specs.git'

target 'URBNAlert', :exclusive => true do
  pod "URBNAlert", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "URBNAlert", :path => "../"

  pod 'FBSnapshotTestCase'
end
