source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'URBNAlert' do
    target 'Tests' do
    inherit! :search_paths
    end 
end


pod "URBNAlert", :path => "../"
